QUnit.test('Math.hypot', assert => {
  assert.isFunction(Math.hypot);
  assert.name(Math.hypot, 'hypot');
  assert.arity(Math.hypot, 2);
  assert.looksNative(Math.hypot);
  assert.nonEnumerable(Math, 'hypot');
  assert.strictEqual(Math.hypot(), 0);
  assert.strictEqual(Math.hypot(1), 1);
  assert.same(Math.hypot('', 0), 0);
  assert.same(Math.hypot(0, ''), 0);
  assert.strictEqual(Math.hypot(Infinity, 0), Infinity, 'Infinity, 0');
  assert.strictEqual(Math.hypot(-Infinity, 0), Infinity, '-Infinity, 0');
  assert.strictEqual(Math.hypot(0, Infinity), Infinity, '0, Infinity');
  assert.strictEqual(Math.hypot(0, -Infinity), Infinity, '0, -Infinity');
  assert.strictEqual(Math.hypot(Infinity, NaN), Infinity, 'Infinity, NaN');
  assert.strictEqual(Math.hypot(NaN, -Infinity), Infinity, 'NaN, -Infinity');
  assert.same(Math.hypot(NaN, 0), NaN, 'NaN, 0');
  assert.same(Math.hypot(0, NaN), NaN, '0, NaN');
  assert.same(Math.hypot(0, -0), 0);
  assert.same(Math.hypot(0, 0), 0);
  assert.same(Math.hypot(-0, -0), 0);
  assert.same(Math.hypot(-0, 0), 0);
  assert.strictEqual(Math.hypot(0, 1), 1);
  assert.strictEqual(Math.hypot(0, -1), 1);
  assert.strictEqual(Math.hypot(-0, 1), 1);
  assert.strictEqual(Math.hypot(-0, -1), 1);
  assert.same(Math.hypot(0), 0);
  assert.strictEqual(Math.hypot(1), 1);
  assert.strictEqual(Math.hypot(2), 2);
  assert.strictEqual(Math.hypot(0, 0, 1), 1);
  assert.strictEqual(Math.hypot(0, 1, 0), 1);
  assert.strictEqual(Math.hypot(1, 0, 0), 1);
  assert.strictEqual(Math.hypot(2, 3, 4), Math.sqrt(2 * 2 + 3 * 3 + 4 * 4));
  assert.strictEqual(Math.hypot(2, 3, 4, 5), Math.sqrt(2 * 2 + 3 * 3 + 4 * 4 + 5 * 5));
  assert.epsilon(Math.hypot(66, 66), 93.33809511662427);
  assert.epsilon(Math.hypot(0.1, 100), 100.0000499999875);
  assert.strictEqual(Math.hypot(1e+300, 1e+300), 1.4142135623730952e+300);
  assert.strictEqual(Math.floor(Math.hypot(1e-300, 1e-300) * 1e308), 141421356);
  assert.strictEqual(Math.hypot(1e+300, 1e+300, 2, 3), 1.4142135623730952e+300);
  assert.strictEqual(Math.hypot(-3, 4), 5);
  assert.strictEqual(Math.hypot(3, -4), 5);
});
